defaults: grpo_math_1B.yaml

checkpointing:
  checkpoint_dir: "results/grpo0.5B-gsm8k-b32-r64-fp02-fn00"

grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 64

policy:
  model_name: "/n/fs/vision-mix/rm4411/hf_models/Qwen2.5-0.5B"
  train_global_batch_size: 2048

data:
  _override_: true
  max_input_seq_length: ${policy.max_total_sequence_length}
  shuffle: true
  num_workers: 1
  use_multiple_dataloader: false

  train:
    dataset_name: "gsm8k"
    split: train

  validation:
    dataset_name: "gsm8k"
    split: test

  default:
    prompt_file: null
    system_prompt_file: "examples/prompts/gsm8k.txt"
    processor: "math_hf_data_processor"
    env_name: "math"

env:
  math:
    fp: 0.2
    fn: 0.0

logger:
  log_dir: "logs_0.5B"
  wandb:
    name: "grpo0.5B-gsm8k-b32-r64-fp02-fn00"
