defaults: grpo_math_1B.yaml

checkpointing:
  checkpoint_dir: "results/0.5Bgrpo_gsm8k_b16_r64_p0.1"

grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 64

policy:
  train_global_batch_size: 1024

data:
  _override_: true
  max_input_seq_length: ${policy.max_total_sequence_length}
  shuffle: true
  num_workers: 1
  use_multiple_dataloader: false

  train:
    dataset_name: "gsm8k"
    split: train

  validation:
    dataset_name: "gsm8k"
    split: test

  default:
    prompt_file: null
    system_prompt_file: "examples/prompts/gsm8k.txt"
    processor: "math_hf_data_processor"
    env_name: "math"

env:
  math:
    p: 0.1

logger:
  log_dir: "logs_0.5B"
  wandb:
    name: "grpo0.5B-gsm8k-b16-r64-p0.1"
